using System;
using System.Text.Json.Serialization;
using Sinch.Conversation.Common;
using Sinch.Conversation.Events;

namespace Sinch.Conversation.Conversations.InjectEvent
{
    public class InjectEventRequest
    {
        /// <summary>
        ///     The unique ID of the conversation. This is generated by the system.
        /// </summary>
        [JsonIgnore]
#if NET7_0_OR_GREATER
        public required string ConversationId { get; set; }
#else
        public string ConversationId { get; set; }
#endif

        /// <summary>
        ///     The content of the events.
        /// </summary>
#if NET7_0_OR_GREATER
        public required ConversationEventEvent Event { get; set; }
#else
        public ConversationEventEvent Event { get; set; }
#endif

        /// <summary>
        ///     The processed time of the message in UTC timezone. Must be less than current_time and greater than (current_time -
        ///     30 days).
        /// </summary>
#if NET7_0_OR_GREATER
        public required DateTime AcceptTime { get; set; }
#else
        public DateTime AcceptTime { get; set; }
#endif

        /// <summary>
        ///     Optional. The ID of the contact. Will not be present for apps in Dispatch Mode.
        /// </summary>
        public string ContactId { get; set; }

        /// <summary>
        ///     A unique identity of message recipient on a particular channel. For example, the channel identity on SMS, WHATSAPP
        ///     or VIBERBM is a MSISDN phone number.
        /// </summary>
        public ChannelIdentity ChannelIdentity { get; set; }

        /// <summary>
        ///     Whether or not Conversation API should store contacts and conversations for the app. For more information, see
        ///     [Processing Modes](https://developers.sinch.com/docs/conversation/processing-modes/).
        /// </summary>
        public ProcessingMode ProcessingMode { get; set; }
    }
}
