using System.Collections.Generic;
using Sinch.Voice.Calls.Actions;
using Sinch.Voice.Calls.Instructions;

namespace Sinch.Voice.Calls.Update
{
    public class UpdateCallRequest
    {
        /// <summary>
        ///     The unique identifier of the call. This value is generated by the system.
        ///     <example>4398599d1ba84ef3bde0a82dfb61abed</example>
        /// </summary>

        public required string CallId { get; set; }


        /// <summary>
        ///     The collection of instructions that can perform various tasks during the call. You can include as many instructions
        ///     as necessary.
        /// </summary>
        public List<IInstruction>? Instructions { get; set; }

        /// <summary>
        ///     The action that will control the call. Each SVAML object can only include one action.
        /// </summary>
        public IAction? Action { get; set; }
    }
}
