<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ListForNumber</RootNamespace>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)'!='Debug'">
        <PackageReference Include="Sinch" Version="*" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <ProjectReference Include="..\..\..\..\..\src\Sinch\Sinch.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Shared\SnippetsConfig.Shared.csproj" />
    </ItemGroup>
</Project>
