apiRules:
  - exclude:
      uidRegex: ^Sinch\.Auth
  - exclude:
      uidRegex: Converter
  - exclude:
      uidRegex: ^Sinch\.Logger
  - exclude:
      uidRegex: ^Sinch\.Core\.EmptyResponse
  - exclude:
      uidRegex: ^Sinch\.Core\.JsonExtensions
