name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dotnet-version: "8.0.x"
            tfm: net8.0
          - dotnet-version: "9.0.x"
            tfm: net9.0
          - dotnet-version: "10.0.x"
            tfm: net10.0

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          # NOTE!: https://github.com/GitTools/GitVersion/issues/3614 from tag branch gitversion appends suffix 
          # of tags-v*** which breaks publish right after tag branch build
          versionSpec: '5.11.x'

      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Setup .NET SDK
        id: dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Checkout mockserver e2e
        uses: actions/checkout@v4
        with:
          repository: sinch/sinch-sdk-mockserver
          token: ${{ secrets.MOCKSERVER_REPO_PAT_CI }}
          ref: main
          path: sinch-sdk-mockserver

      - name: Copy feature files from mockserver
        run: |
          mkdir -p tests/Sinch.Tests.Features/features/numbers
          mkdir -p tests/Sinch.Tests.Features/features/sms
          mkdir -p tests/Sinch.Tests.Features/features/voice
          mkdir -p tests/Sinch.Tests.Features/features/verification
          mkdir -p tests/Sinch.Tests.Features/features/conversation
          mkdir -p tests/Sinch.Tests.Features/features/fax
          
          # Copy feature files we support
          cp sinch-sdk-mockserver/features/numbers/available-regions.feature tests/Sinch.Tests.Features/features/numbers/
          cp sinch-sdk-mockserver/features/numbers/callback-configuration.feature tests/Sinch.Tests.Features/features/numbers/
          cp sinch-sdk-mockserver/features/numbers/numbers.feature tests/Sinch.Tests.Features/features/numbers/
          cp sinch-sdk-mockserver/features/numbers/webhooks.feature tests/Sinch.Tests.Features/features/numbers/

          cp sinch-sdk-mockserver/features/sms/*.feature tests/Sinch.Tests.Features/features/sms/
          cp sinch-sdk-mockserver/features/voice/*.feature tests/Sinch.Tests.Features/features/voice/
          cp sinch-sdk-mockserver/features/verification/*.feature tests/Sinch.Tests.Features/features/verification/

          cp sinch-sdk-mockserver/features/conversation/apps.feature tests/Sinch.Tests.Features/features/conversation/
          cp sinch-sdk-mockserver/features/conversation/capability.feature tests/Sinch.Tests.Features/features/conversation/
          cp sinch-sdk-mockserver/features/conversation/transcoding.feature tests/Sinch.Tests.Features/features/conversation/
          cp sinch-sdk-mockserver/features/conversation/contacts.feature tests/Sinch.Tests.Features/features/conversation/

          cp sinch-sdk-mockserver/features/fax/services.feature tests/Sinch.Tests.Features/features/fax/
          cp sinch-sdk-mockserver/features/fax/emails.feature tests/Sinch.Tests.Features/features/fax/
          cp sinch-sdk-mockserver/features/fax/faxes.feature tests/Sinch.Tests.Features/features/fax/

      - name: Run mockserver docker-compose
        run: docker compose up -d
        working-directory: sinch-sdk-mockserver
        
      - name: Install dependencies
        run: dotnet restore

      - name: Check Formatting
        run: dotnet format --verify-no-changes --verbosity diagnostic
        
      - name: Build
        run: dotnet build --framework ${{ matrix.tfm }} -p:Version=${{ steps.gitversion.outputs.semVer }} --configuration Release --no-restore

      - name: Build Examples
        run: dotnet build examples/dirs.proj

      - name: Test
        run: dotnet test tests/Sinch.Tests --framework ${{ matrix.tfm }} --no-restore --verbosity normal

      - name: Test e2e
        run: dotnet test tests/Sinch.Tests.Features --framework ${{ matrix.tfm }} --no-restore --verbosity normal

  pack:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.11.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install dependencies
        run: dotnet restore

      # --include-symbols?
      - name: Pack
        run: dotnet pack --configuration Release src/Sinch -p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -p:Version=${{ steps.gitversion.outputs.semVer }} --no-restore

      - name: Archive nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: src/Sinch/bin/Release/*.nupkg
          if-no-files-found: error
